# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = [
  ".conform.yaml",
  ".gitignore",
  "CHANGELOG.md",
  "README.md",
  "app/.gitignore",
  "app/proguard-rules.pro",
  "docs/DEVELOPMENT.md",
  "feature/home/.gitignore",
  "feature/home/consumer-rules.pro",
  "feature/home/proguard-rules.pro",
  "gradle/libs.versions.toml",
  "gradle/wrapper/gradle-wrapper.properties",
  "gradle.properties",
  "renovate.json",
  "settings.gradle.kts",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Digg - Agency for Digital Government"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
  "**/*.kt",
  "**/*.kts",
  "**/*.xml",
  "**/*.ttf",
  "**/*.png",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Digg - Agency for Digital Government"
SPDX-License-Identifier = "EUPL-1.2"

[[annotations]]
path = [
  "gradlew",
  "gradlew.bat",
  "gradle/wrapper/gradle-wrapper.jar",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Gradle Inc."
SPDX-License-Identifier = "Apache-2.0"
