[versions]
agp = "8.13.1"
kotlin = "2.2.21"
ktlint = "1.8.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
ktlintCompose = "0.5.6"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
composeBom = "2025.12.01"
appcompat = "1.7.1"
material = "1.13.0"
navigationCompose = "2.9.6"
timber = "5.0.1"
eudi-openid4vci = "0.9.1"
eudi-openid4vp = "0.11.1"
ktor = "3.3.0"
nimbus = "10.5"
coil = "3.3.0"
datastore = "1.2.0"
serializationJson = "1.9.0"
room = "2.8.4"
ksp = "2.2.10-2.0.2"
hilt = "2.57.2"
hiltNavigationCompose = "1.3.0"
fabrikt = "1.24.0"
androidBrowser = "1.9.0"
kotlinter = "5.4.0"

[libraries]
#Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

#Android core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "androidBrowser" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
ktlint-compose = { group = "io.nlopez.compose.rules", name = "ktlint", version.ref = "ktlintCompose" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }


#Storage
datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJson" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

#Network - Ktor
ktor-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }
ktor-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

#Logging
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

#Eudi
eudi-openid4vci = { group = "eu.europa.ec.eudi", name = "eudi-lib-jvm-openid4vci-kt", version.ref = "eudi-openid4vci" }
eudi-openid4vp = { group = "eu.europa.ec.eudi", name = "eudi-lib-jvm-siop-openid4vp-kt", version.ref = "eudi-openid4vp" }
nimbus = { group = "com.nimbusds", name = "nimbus-jose-jwt", version.ref = "nimbus" }

#Image
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }

#Dependency Injection
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

[bundles]
images = ["coil-compose", "coil-network"]
eudi = ["eudi-openid4vci", "eudi-openid4vp", "nimbus", "ktor-okhttp", "ktor-core", "ktor-logging", "ktor-content-negotiation", "ktor-serialization"]
storage = ["datastore", "kotlinx-serialization-json"]
di = ["hilt-android", "hilt-navigation-compose"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
fabrikt = { id = "ch.acanda.gradle.fabrikt", version.ref = "fabrikt" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
